# Generated by Django 4.0 on 2021-12-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('posts', '0002_alter_post_es_borrador_alter_post_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
