# Generated by Django 3.2.9 on 2021-12-17 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_rename_descripcion_post_cuerpo_remove_post_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='comentarios',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
