# Generated by Django 4.0 on 2021-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='writer',
            field=models.BooleanField(default=False),
        ),
    ]
