# Generated by Django 4.0 on 2021-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comment',
            field=models.BooleanField(default=True),
        ),
    ]
